name: OneFlow CI/CD

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'feature/*'
      - 'release/*'
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'feature/*'
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          echo "Deploying to production server..."
